require("ton1czech.plugins")
require("ton1czech.core.options")
require("ton1czech.core.keymaps")
require("ton1czech.core.colorscheme")
require("ton1czech.plugins.comment")
require("ton1czech.plugins.nvim-tree")
